version: '3.9'
services:
  db:
    image: mysql:8.0.32
    command: mysqld --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      TZ: Europe/Lisbon
      MYSQL_ROOT_PASSWORD: admin12345
      MYSQL_USER: docker
      MYSQL_PASSWORD: admin12345
      MYSQL_DATABASE: rest_with_spring_boot_erudio
      MYSQL_ROOT_HOST: '%'
      MYSQL_TCP_PORT: 3308
    ports:
      - 3308:3308
    expose:
      - 3308
    networks:
      - luisberardo-network
  rest-with-spring-boot-erudio:
    image: luisberardo/rest-with-spring-boot-erudio
    restart: always
    build: ./21_FileUploadAndDownload&22_Docker
    working_dir: /21_FileUploadAndDownload&22_Docker
    environment:
      TZ: Europe/Lisbon
      SPRING.DATASOURCE.URL: jdbc:mysql://db:3308/rest_with_spring_boot_erudio?useTimezone=true&serverTimezone=UTC
      SPRING.DATASOURCE.USERNAME: root
      SPRING.DATASOURCE.PASSWORD: admin12345
    ports:
      - 80:80
    command: mvn spring-boot:run
    depends_on:
      - db
    networks:
      - luisberardo-network
networks:
  luisberardo-network:
    driver: bridge